# Go cross compiler (xgo): Wildcard layer to the latest 1.4 release
# Copyright (c) 2014 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM niklaskhf/xgo-1.4.2

MAINTAINER Péter Szilágyi <peterke@gmail.com>
