# Go cross compiler (xgo): Wildcard layer to the latest 1.7 release
# Copyright (c) 2016 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM niklaskhf/xgo-1.7.5

MAINTAINER Péter Szilágyi <peterke@gmail.com>
